//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aktivgeschaeft_01_SelectFolder
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DialogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KRM_FileSearch.DialogStrings", typeof(DialogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung ausgeben, falls nicht die aktuelle Vorlagenversion verwendet wird?.
        /// </summary>
        internal static string checkboxAktivate_Version_Warning {
            get {
                return ResourceManager.GetString("checkboxAktivate_Version_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semikolon.
        /// </summary>
        internal static string comboboxColumn_Delimiter_1 {
            get {
                return ResourceManager.GetString("comboboxColumn_Delimiter_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        internal static string comboboxColumn_Delimiter_2 {
            get {
                return ResourceManager.GetString("comboboxColumn_Delimiter_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VR-Control KRM Stand dd.mm.2021.
        /// </summary>
        internal static string comboboxVersion_Importdefinition_1 {
            get {
                return ResourceManager.GetString("comboboxVersion_Importdefinition_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VR-Control KRM Stand 17.05.2022.
        /// </summary>
        internal static string comboboxVersion_Importdefinition_2 {
            get {
                return ResourceManager.GetString("comboboxVersion_Importdefinition_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die ausgewählte Datei konnte nicht gefunden werden. Bitte überprüfen Sie Ihre Eingaben..
        /// </summary>
        internal static string error_FileNotFound {
            get {
                return ResourceManager.GetString("error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Eingaben wurden gespeichert..
        /// </summary>
        internal static string info_SaveMessage {
            get {
                return ResourceManager.GetString("info_SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaltentrennzeichen.
        /// </summary>
        internal static string lableColumn_Delimiter {
            get {
                return ResourceManager.GetString("lableColumn_Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorlagenversion.
        /// </summary>
        internal static string lableVersion_ImportDefinition {
            get {
                return ResourceManager.GetString("lableVersion_ImportDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie verwenden nicht die aktuelle Version der Importvorlage. Bitte prüfen Sie Ihre Auswahl!.
        /// </summary>
        internal static string warning_Latest_Version {
            get {
                return ResourceManager.GetString("warning_Latest_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre gespeicherten Eingaben konnten nicht wieder hergestellt werden. Bitte wählen Sie einen neuen Wert aus und speichern erneut..
        /// </summary>
        internal static string warning_SaveEntriesNotFound {
            get {
                return ResourceManager.GetString("warning_SaveEntriesNotFound", resourceCulture);
            }
        }
    }
}
