//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aktivgeschaeft_01_SelectFolder {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DialogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KRM_FileSearch.DialogStrings", typeof(DialogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warnung ausgeben, falls nicht die aktuelle Vorlagenversion verwendet wird? ähnelt.
        /// </summary>
        internal static string checkboxAktivate_Version_Warning {
            get {
                return ResourceManager.GetString("checkboxAktivate_Version_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Semikolon ähnelt.
        /// </summary>
        internal static string comboboxColumn_Delimiter_1 {
            get {
                return ResourceManager.GetString("comboboxColumn_Delimiter_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tab ähnelt.
        /// </summary>
        internal static string comboboxColumn_Delimiter_2 {
            get {
                return ResourceManager.GetString("comboboxColumn_Delimiter_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VR-Control KRM Stand dd.mm.2021 ähnelt.
        /// </summary>
        internal static string comboboxVersion_Importdefinition_1 {
            get {
                return ResourceManager.GetString("comboboxVersion_Importdefinition_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VR-Control KRM Stand 17.05.2022 ähnelt.
        /// </summary>
        internal static string comboboxVersion_Importdefinition_2 {
            get {
                return ResourceManager.GetString("comboboxVersion_Importdefinition_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die ausgewählte Datei konnte nicht gefunden werden. Bitte überprüfen Sie Ihre Eingaben. ähnelt.
        /// </summary>
        internal static string error_FileNotFound {
            get {
                return ResourceManager.GetString("error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihre Eingaben wurden gespeichert. ähnelt.
        /// </summary>
        internal static string info_SaveMessage {
            get {
                return ResourceManager.GetString("info_SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spaltentrennzeichen ähnelt.
        /// </summary>
        internal static string lableColumn_Delimiter {
            get {
                return ResourceManager.GetString("lableColumn_Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorlagenversion ähnelt.
        /// </summary>
        internal static string lableVersion_ImportDefinition {
            get {
                return ResourceManager.GetString("lableVersion_ImportDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie verwenden nicht die aktuelle Version der Importvorlage. Bitte prüfen Sie Ihre Auswahl! ähnelt.
        /// </summary>
        internal static string warning_Latest_Version {
            get {
                return ResourceManager.GetString("warning_Latest_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihre gespeicherten Eingaben konnten nicht wieder hergestellt werden. Bitte wählen Sie einen neuen Wert aus und speichern erneut. ähnelt.
        /// </summary>
        internal static string warning_SaveEntriesNotFound {
            get {
                return ResourceManager.GetString("warning_SaveEntriesNotFound", resourceCulture);
            }
        }
    }
}
